import { test, expect, type Page } from '@playwright/test';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { Client } from 'pg';
import { readFileSync } from 'node:fs';
const url = process.env.SUPABASE_URL || '';
const key = process.env.AUTH_TEST_SERVICE_KEY || '';
const database = process.env.AUTH_TEST_DATABASE_URL || '';
// No skips: missing local infrastructure must be an explicit test failure.
let admin: SupabaseClient;
test.beforeAll(() => {
  if (![url,database].every(v => v && ['localhost','127.0.0.1'].includes(new URL(v).hostname)) || !key) throw new Error('Run npm run test:auth:integration with disposable local Supabase running.');
  admin = createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
});
const password = 'Synthetic-Test-Password-123!';
async function login(page: Page, email: string, pass = password) {
  await page.goto('/login');
  await page.locator('main form').first().getByLabel('School email address').fill(email);
  await page.getByLabel('Password',{exact:true}).fill(pass);
  await page.getByRole('button',{name:'Log in',exact:true}).click();
  await expect(page).toHaveURL(/\/account$/);
}

test('real signup, email confirmation, team approval, suspension and password recovery', async ({page,browser}) => {
  const suffix = Date.now();
  const email = `teacher-${suffix}@synthetic-school.example`;
  const reviewerEmail = `reviewer-${suffix}@reviseit.example`;
  const db = new Client({connectionString:database});
  await db.connect();
  const { data: reviewer, error: reviewerError } = await admin.auth.admin.createUser({email:reviewerEmail,password,email_confirm:true});
  expect(reviewerError).toBeNull();
  await db.query('insert into private.account_reviewers(user_id) values($1)',[reviewer.user!.id]);
  const reviewContext = await browser.newContext();
  const reviewPage = await reviewContext.newPage();
  try {
    await page.goto('/register');
    await page.getByLabel('Your full name').fill('Synthetic Teacher');
    await page.getByLabel('School name',{exact:true}).fill('Synthetic School');
    await page.getByLabel('Department',{exact:true}).fill('Physical Sciences');
    await page.getByLabel('School email address').fill(email);
    await page.getByLabel('Password',{exact:true}).fill(password);
    await page.getByRole('button',{name:'Create account',exact:true}).click();
    await expect(page.getByRole('status')).toContainText('Check your school email');
    await page.goto('/login');
    await page.locator('main form').first().getByLabel('School email address').fill(email);
    await page.getByLabel('Password',{exact:true}).fill(password);
    await page.getByRole('button',{name:'Log in',exact:true}).click();
    await expect(page.getByRole('main').getByRole('alert')).toContainText('confirm your school email first');
    // Retrieve a local-only signup link through the admin test client; real hosted email delivery is a separate smoke check.
    const {data:confirmation,error:linkError} = await admin.auth.admin.generateLink({type:'signup',email,password});
    expect(linkError).toBeNull();
    await page.goto(`/auth/confirm?token_hash=${confirmation.properties!.hashed_token}&type=signup`);
    await page.getByRole('button',{name:'Continue',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Your account is awaiting verification'})).toBeVisible();
    await page.goto('/teacher');
    await expect(page).toHaveURL(/\/account$/);
    expect((await page.request.get('/api/teacher/session')).status()).toBe(403);
    await login(reviewPage,reviewerEmail);
    await reviewPage.getByRole('link',{name:'Review school accounts'}).click();
    await reviewPage.getByText('Add a verified school department',{exact:true}).click();
    const schoolForm = reviewPage.locator('details form');
    await schoolForm.getByLabel('Full school name').fill('Synthetic School');
    await schoolForm.getByLabel('School identifier').fill('synthetic-school');
    await schoolForm.getByLabel('Department',{exact:true}).fill('Physical Sciences');
    await schoolForm.getByRole('button',{name:'Save school department'}).click();
    await expect(schoolForm.getByRole('status')).toContainText('available');
    const account = reviewPage.locator('article').filter({hasText:email});
    await account.getByRole('combobox',{name:/^Decision/}).selectOption('approved');
    await account.getByLabel('Verified school and department').selectOption({label:'Synthetic School · Physical Sciences'});
    await account.getByLabel('Verification evidence or reason').fill('Confirmed affiliation using synthetic test evidence.');
    await account.getByRole('button',{name:'Save verification decision'}).click();
    await expect(account.getByRole('status')).toContainText('Decision saved');
    await db.query(readFileSync('tests/fixtures/workspace.sql','utf8'));
    await db.query("insert into public.school_curriculum_access(school_id,module_id) select school_id,m.id from public.teacher_accounts cross join public.curriculum_modules m where user_id=$1",[(await db.query('select id from auth.users where email=$1',[email])).rows[0].id]);
    await page.goto('/teacher');
    await expect(page.getByRole('heading',{name:'Plan your next paper'})).toBeVisible();
    const diagram=page.getByRole('img',{name:'Velocity against time graph with a rising line followed by a horizontal line'});
    await expect(diagram).toBeVisible();
    await expect.poll(()=>diagram.evaluate((image:HTMLImageElement)=>image.naturalWidth)).toBeGreaterThan(0);
    const diagramUrl=(await diagram.getAttribute('src'))!;
    expect((await page.request.get(diagramUrl)).status()).toBe(200);
    await page.getByRole('searchbox').fill('Grade 11 electricity');
    await expect(page.getByRole('button',{name:'Browse Grade 11 Physical Sciences · demonstration'})).toBeVisible();
    await page.getByRole('button',{name:'Clear search'}).click();
    const outlineCard=page.getByRole('article',{name:'Reading a motion graph'});
    await expect(outlineCard.getByText('3–5 subquestions')).toBeVisible();
    await outlineCard.getByRole('button',{name:'Reveal more'}).click();
    await expect(outlineCard.getByText('Remember',{exact:true})).toBeVisible();
    await page.getByLabel('Select Reading a motion graph').check();
    await page.getByRole('button',{name:'Save selection',exact:true}).click();
    await expect(page.getByRole('status')).toContainText('selection is saved');
    await page.reload();
    await expect(page.getByLabel('Select Reading a motion graph')).toBeChecked();
    await page.getByRole('button',{name:'School formatting',exact:true}).click();
    await page.getByLabel('School heading').fill('SYNTHETIC SCHOOL SCIENCE');
    await page.getByRole('button',{name:'Save school formatting'}).click();
    await expect(page.getByRole('status')).toContainText('School formatting saved');
    await page.reload();
    await page.getByRole('button',{name:'School formatting',exact:true}).click();
    await expect(page.getByLabel('School heading')).toHaveValue('SYNTHETIC SCHOOL SCIENCE');
    await page.getByRole('combobox',{name:'Curriculum',exact:true}).selectOption('demo-grade-11-sciences');
    await expect(page.getByLabel('School heading')).toHaveValue('');
    await page.getByRole('button',{name:'Question catalogue'}).click();
    await expect(page.getByLabel('Select Interpreting a force diagram')).not.toBeChecked();
    const catalogueResponse=await page.request.get('/api/teacher/workspace');
    expect(catalogueResponse.status()).toBe(200);
    expect(await catalogueResponse.text()).not.toMatch(/parameter_questions|specification|generation_prompt/);
    await page.screenshot({path:'test-results/teacher-workspace-desktop.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await expect(page.getByRole('heading',{name:'Selection summary'})).toBeVisible();
    await page.screenshot({path:'test-results/teacher-workspace-mobile.png',fullPage:true});
    expect((await page.request.get('/api/teacher/session')).status()).toBe(200);
    await account.getByRole('combobox',{name:/^Decision/}).selectOption('suspended');
    await account.getByLabel('Verification evidence or reason').fill('Synthetic suspension test.');
    await account.getByRole('button',{name:'Save verification decision'}).click();
    await expect(account.getByText('Status: suspended')).toBeVisible();
    expect((await page.request.get('/api/teacher/session')).status()).toBe(403);
    expect((await page.request.get('/api/teacher/workspace')).status()).toBe(403);
    expect((await page.request.get('/api/teacher/catalogue/search?q=electricity')).status()).toBe(403);
    expect((await page.request.get(diagramUrl)).status()).toBe(403);
    await page.goto('/teacher');
    await expect(page.getByRole('heading',{name:'Your account access is paused'})).toBeVisible();
    await page.getByRole('button',{name:'Log out',exact:true}).click();
    await expect(page).toHaveURL(/\/login$/);
    const {data:recovery,error:recoveryError} = await admin.auth.admin.generateLink({type:'recovery',email});
    expect(recoveryError).toBeNull();
    await page.goto(`/auth/confirm?token_hash=${recovery.properties!.hashed_token}&type=recovery`);
    await page.getByRole('button',{name:'Continue',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Choose a new password'})).toBeVisible();
    await page.getByLabel('Password',{exact:true}).fill(`${password}new`);
    await page.getByLabel('Confirm password',{exact:true}).fill(`${password}new`);
    await page.getByRole('button',{name:'Save password'}).click();
    await expect(page).toHaveURL(/\/login\?message=password-updated$/);
    await login(page,email,`${password}new`);
    await expect(page.getByRole('heading',{name:'Your account access is paused'})).toBeVisible();
  } finally { await Promise.allSettled([reviewContext.close(), db.end()]); }
});
