import { describe,it,expect } from 'vitest';
import { answersMatchQuestionnaire,isQuestionnaire,isQuestionnaireAnswers,type Questionnaire,type QuestionnaireAnswers } from '../../lib/jobs/questionnaire';
const revision='a'.repeat(64);
export const form:Questionnaire={schemaVersion:2,revision,items:[{id:'line_1',title:'First selected question',marks:8,fields:[{id:'scenario',label:'Choose a setting',hint:'Authored hint',required:true,allowAutomatic:false,type:'choice',allowOther:false,choices:[{id:'a',label:'First setting'},{id:'b',label:'Second setting'}]}]},{id:'line_2',title:'Second selected question',marks:12,fields:[{id:'scenario',label:'Choose a setting',hint:'',required:false,allowAutomatic:true,type:'choice',allowOther:true,choices:[{id:'c',label:'Different setting'}]}]}],paperFields:[{id:'notes',label:'Paper notes',hint:'',type:'text',required:false,allowAutomatic:false,maxLength:100}]};
const answers:QuestionnaireAnswers={schemaVersion:2,revision,items:{line_1:{scenario:{kind:'choice',choiceId:'a'}},line_2:{scenario:{kind:'automatic'}}},paper:{notes:{kind:'omit'}}};
describe('purchase-scoped grouped questionnaire contract',()=>{
 it('keeps repeated field identifiers scoped to their question',()=>{expect(answersMatchQuestionnaire(form,answers)).toBe(true);const a=structuredClone(answers);a.items.line_1.scenario={kind:'choice',choiceId:'c'};expect(answersMatchQuestionnaire(form,a)).toBe(false);});
 it('rejects unexpected private metadata at every form level',()=>{for(const edit of [(x:any)=>x.source='private.md',(x:any)=>x.items[0].specification='secret',(x:any)=>x.items[0].fields[0].prompt='secret',(x:any)=>x.items[0].fields[0].choices[0].source='secret']){const f=structuredClone(form);edit(f);expect(isQuestionnaire(f)).toBe(false);}});
 it('binds exact sections, fields and form revision',()=>{for(const edit of [(x:any)=>x.revision='b'.repeat(64),(x:any)=>delete x.items.line_2,(x:any)=>x.items.extra={},(x:any)=>x.paper.extra={kind:'omit'},(x:any)=>delete x.items.line_1.scenario]){const a=structuredClone(answers);edit(a);expect(answersMatchQuestionnaire(form,a)).toBe(false);}});
 it('permits automatic, omission and own words only where explicitly authored',()=>{const a=structuredClone(answers);a.items.line_1.scenario={kind:'automatic'};expect(answersMatchQuestionnaire(form,a)).toBe(false);a.items.line_1.scenario={kind:'omit'};expect(answersMatchQuestionnaire(form,a)).toBe(false);a.items.line_1.scenario={kind:'text',text:'invented option'};expect(answersMatchQuestionnaire(form,a)).toBe(false);a.items.line_1.scenario=answers.items.line_1.scenario;a.items.line_2.scenario={kind:'text',text:'Teacher preference'};expect(answersMatchQuestionnaire(form,a)).toBe(true);});
 it('rejects malformed answer variants and prototype property names',()=>{for(const value of [{kind:'omit',text:'hidden'},{kind:'choice',choiceId:'a',source:'private'},{kind:'text',text:12}]){const a:any=structuredClone(answers);a.paper.notes=value;expect(isQuestionnaireAnswers(a)).toBe(false);}const a:any=structuredClone(answers);a.items.constructor={};expect(isQuestionnaireAnswers(a)).toBe(false);});
 it('enforces text bounds and required text content',()=>{const a=structuredClone(answers);a.paper.notes={kind:'text',text:'x'.repeat(101)};expect(answersMatchQuestionnaire(form,a)).toBe(false);const f=structuredClone(form);f.paperFields[0].required=true;a.paper.notes={kind:'text',text:'  '};expect(answersMatchQuestionnaire(f,a)).toBe(false);});
 it('rejects duplicate questions, fields, choices and invalid marks',()=>{for(const edit of [(x:any)=>x.items.push(x.items[0]),(x:any)=>x.items[0].fields.push(x.items[0].fields[0]),(x:any)=>x.items[0].fields[0].choices.push(x.items[0].fields[0].choices[0]),(x:any)=>x.items[0].marks=1.5]){const f=structuredClone(form);edit(f);expect(isQuestionnaire(f)).toBe(false);}});
 it('supports an explicitly empty item section without treating it as missing',()=>{const f=structuredClone(form);f.items[1].fields=[];const a=structuredClone(answers);a.items.line_2={};expect(isQuestionnaire(f)).toBe(true);expect(answersMatchQuestionnaire(f,a)).toBe(true);});
 it('bounds the encoded request size, including multibyte teacher text',()=>{const a:QuestionnaireAnswers={schemaVersion:2,revision,items:{},paper:{}};for(let i=0;i<20;i++)a.paper['field_'+i]={kind:'text',text:'漢'.repeat(1500)};expect(JSON.stringify(a).length).toBeLessThan(64000);expect(isQuestionnaireAnswers(a)).toBe(false);});
 it('supports the three-question form size beyond the old flat limit',()=>{const f=structuredClone(form);f.items=Array.from({length:3},(_,i)=>({...form.items[0],id:'line_'+i,fields:Array.from({length:12},(_,j)=>({...form.items[0].fields[0],id:'field_'+j}))}));expect(isQuestionnaire(f)).toBe(true);});
});
